project_id = "hmdnronxajctsrlgrhey"

[functions.chat-response]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.consultation-webhook-proxy]
verify_jwt = false

[functions.create-booking-checkout]
verify_jwt = false
